# -*- coding: utf-8 -*-
"""Store Sales Analysis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LdkzaTf4yJZrEC92jzRYG87twmJfcSux

# **Project Name :** Store Sales Analysis
### **Name** : Shreyans Jain

### **Project Summary -**

The Store Sales Analysis project focuses on analyzing and visualizing sales data from a retail store to gain insights into sales performance, trends, and customer behavior. By examining various aspects of the store's sales data, the project aims to provide actionable insights that can guide business decisions and strategies.

### **Project Objectives:**

*  Analyze historical sales data to identify trends, patterns, and seasonality.
*   Explore sales performance across different products, categories, and time periods.
*   Identify high-performing products and low-performing products.
*   Visualize sales data using charts and graphs for better understanding.
*   Provide recommendations for improving sales, optimizing inventory, and enhancing customer experience.


### **Project Steps:**

**Data Collection:** Gather sales data from the retail store's records, including information about products, categories, prices, quantities sold, dates, and customer details.

**Data Cleaning:** Clean and preprocess the data by handling missing values, duplicates, and inconsistencies. Convert data types as needed for analysis.

**Exploratory Data Analysis (EDA):** Perform exploratory analysis to understand the distribution of sales, identify outliers, and explore relationships between variables.

**Sales Trends and Patterns:** Analyze sales trends over time (daily, monthly, yearly) to identify any seasonality, spikes, or dips in sales.

**Customer Behavior:** Analyze customer purchasing behavior, such as repeat purchases, average transaction values, and customer demographics.

**Visualizations:** Create visualizations such as line charts, bar charts, pie charts, and heatmaps to present key findings and insights effectively.

**Recommendations:** Based on the analysis, provide actionable recommendations to improve sales, optimize inventory, and enhance customer satisfaction.

## **Importing Libraries**
"""

# Commented out IPython magic to ensure Python compatibility.
# import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
# %matplotlib inline
from datetime import datetime
import seaborn as sns

"""## **Dataset Loading**

"""

# import data
from google.colab import drive
drive.mount('/content/drive')

df = pd.read_csv("/content/drive/MyDrive/DS/Project/Vrinda Store Data Analysis.csv")

"""## **Dataset First View**"""

df.sample

"""**Dataset Rows & Columns count**

"""

df.shape

"""**Dataset Information**"""

df.info()

"""## **Understanding the variable**"""

df.columns

df.describe()

"""**Check Unique Values for each variable.**"""

df.apply(lambda col : col.unique())

"""## **Data Wrangling**

**From the above info it is clear that there is no null values. While checking samples I noticed that some metrics are clean like in gender Men is represented as "Men" & "M". Let's check them out.**
"""

# checking unique values
df['Gender'].value_counts()

"""**From above, it is clear to better to replace W with Women and M with Men.**"""

# replacing values
df["Gender"].replace('M','Men', inplace=True)
df["Gender"].replace('W','Women', inplace=True)

df['Gender'].value_counts()

"""**Now there is only 2 distinct values in gender column. Now doing same for the Quantity column**"""

# checking unique values
df['Qty'].value_counts()

"""**From above, it is clear to better to replace Two with 2 and One with 1.**"""

# replacing values
df["Qty"].replace('One','1', inplace=True)
df["Qty"].replace('Two', '2', inplace=True)

df['Qty'].value_counts()

"""**Duplicate Values**"""

# checking duplicate values
df.duplicated().sum()

# Remove Duplicates:
# df.drop_duplicates(inplace=True)

"""**I think there is clean data now. Now it would be good if we drop some colums which is not useful for data analysis**"""

# checking unique values
df['currency'].value_counts()

"""**As there is only one currency, so dropping the column "Currency" and dropping the postal code as well, as the state, city is already mentioned.**"""

df.drop(['currency'], axis = 1, inplace=True)
df.drop(['ship-postal-code'], axis = 1, inplace=True)

"""**Change in datatype for required columns**"""

# change datatype
df['Qty'] = df['Qty'] .astype('int64') # changing to integer
df['Date'] = df['Date'].apply(lambda x: datetime.strptime(x,"%d-%m-%Y")) # changing to datetime

"""**Categorizing age in different age group for better analysis**"""

def categorize_age(age):
    if age > 50:
        return "Senior"
    elif age > 30:
        return "Adult"
    else:
        return "Teenager"

# Apply the function to create a new column 'AgeGroup'
df['AgeGroup'] = df['Age'].apply(categorize_age)

print(df)

# checking if the the data of one year or multiple years
df['Date'].dt.year.value_counts()

"""**As the year is only 2022, so making a column "Month" for better Analysis**"""

df['Month'] = df['Date'].dt.month

"""**There is an extra space in the name of the column, replacing it with the correct name (without space)**"""

# renaming the column name
df.rename(columns={"Channel ":"Channel"}, inplace=True)

"""## **Data Vizualization**"""

# Chart-1
# Counting sales on the basis of gender
highest_gender_sales = df.groupby('Gender', as_index=False)['Amount'].sum().rename(columns={'Amount':'Total Sales'})
plt.pie(highest_gender_sales['Total Sales'], labels=highest_gender_sales["Gender"], shadow=True,autopct='%1.1f%%')
plt.title("Gender Sales")
plt.show()

# Chart-2
# Counting sales on the basis of states
plt.figure(figsize=(15,8))
plt.xlabel('State')
plt.ylabel('Sales',fontsize=12)
colors = ['Pink', 'yellow', 'lightblue', 'orange', 'lightgreen']
plt.title("Top 5 States with the Highest Sales")
highest_state_sales = df.groupby('ship-state', as_index=False)['Amount'].sum().sort_values('Amount',ascending=False).rename(columns={'Amount':'Total Sales'})[:5]
plt.barh(highest_state_sales['ship-state'], highest_state_sales['Total Sales'], color= colors)
plt.show()

# Chart-3
# Order Status
Order_stats = df.groupby('Status')['Status'].count()
colors = ['orange', 'lightblue', 'yellow', 'lightgreen']
plt.pie(Order_stats, shadow=True,autopct='%1.1f%%', colors=colors)
plt.title("Order Status")
plt.legend(Order_stats.index)
plt.show()

# Chart-4
# Orders On the Basis of Age Group
plt.figure(figsize=(11,7))
colors = ["#5F4B8BFF", "#E69A8DFF"]
#  plot with countplot
sns.countplot(x=df['AgeGroup'], hue = df['Gender'], palette=colors)
plt.title("Age Group Wise Sales")
plt.xlabel('Age Group')
plt.ylabel('Sales')
plt.show()

# Chart-5
# Channel Sales
Channel_sales = df.groupby("Channel", as_index=False)['Amount'].sum().sort_values('Amount', ascending = False)
plt.figure(figsize=(20,8))
plt.xlabel('Channels')
plt.ylabel("Sales")
plt.title("Different Channel Sales")
sns.barplot(x=Channel_sales["Channel"], y=Channel_sales["Amount"])
plt.show()

"""# **Insights**
1. March witnessed the peak in sales, excluding any transactions that were refunded, returned, or canceled.
2. Women contributed to 64% of the total sales.
3. A significant 92% of the total sales were successfully delivered, while the remaining were either refunded, returned, or canceled.
4. Among the regions, Maharashtra had the highest sales value, followed by Karnataka, Uttar Pradesh, Telangana, and Tamil Nadu.
5. Women between the ages of 30 to 49 showed the highest participation in total sales, accounting for 30% of the overall sales.
6. Amazon led the way with 35.51% of total sales, followed by Myntra and Flipkart.
7. Men were the primary consumers of Western dress, making up 89% of the purchases. Additionally, August recorded the highest sales month.

# **Suggestions**
1. I suggest targeting the women customer within the age group of 30 to 49 from the states of Maharashtra, Karnataka & Uttar Pradesh. It would be great if you target the suggested audience through coupons/ads on  Amazon, Myntra & Flipkart.

2. I suggest to perform marketing strategises on the Men Audience for the Western Dress Products
"""